namespace MutateCSharp.FileSystem;

public static class GeneratedPatterns
{
  public static readonly string AutoGeneratedFilePrefix =
    "TemporaryGeneratedFile_";

  public static readonly string[] AutoGeneratedFileExtensions =
    [".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs"];

  public static readonly string[] AutoGeneratedTriviaPatterns =
    ["<auto-generated", "<autogenerated"];
}